version: '3.4'

services:
  api_nasabah:
    image: khadafi31/bank-khadafi:v.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "44344:80"
    depends_on: 
      - migrations
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "1Secure*Password1"
      ACCEPT_EULA: "Y"
    ports:
    - "14331:1433"
    depends_on: 
      - migrations
  migrations:
    build: 
      context: .
      dockerfile: Migrations.Dockerfile